name: Deploy to SEOhost via SSH

on:
  push:
    branches:
      - main  # Uruchom po zmianach na gałęzi main

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pobierz kod z repozytorium

      - name: Copy files to server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: ./  # Folder lokalny do wysłania
          target: /var/www/html  # Docelowy folder na serwerze

      - name: Execute commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            echo "Deployment complete!"
