name: Deploy to SEOhost via SSH

on:
  push:
    branches:
      - main  # Uruchom po zmianach na gałęzi main

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pobierz kod z repozytorium

      - name: Copy files to server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }} # Jeśli klucz ma hasło
          source: ./  # Folder lokalny do wysłania
          target: ${{ secrets.SSH_TARGET }}  # Docelowy folder na serwerze

      - name: Execute commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }} # Jeśli klucz ma hasło
          script: |
            echo "Starting deployment process"
            cd ${{ secrets.SSH_TARGET }}
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan migrate --force
            echo "Deployment complete!"
